### ISSUE TITLE
spin-rs is now maintained

### ISSUE THREAD

**Issue by zesterer** [rust-osdev/spinning_top#8]
Hello! I've taken over maintenance of `spin-rs`. It now has support for `lock_api` and `Send`/`Sync` guards among other things. I doubt it'll have much bearing on `spinning_top`, but I thought you'd be interested in this (I'm told that `spin-rs`'s lack of maintenance was the primary driving force behind this crate's development).

**Comment by phil-opp** [comment]
Great to hear that! I always liked the crate, so thanks a lot for taking over maintenance!

I still think it's worth keeping `spinning_top` as a simple alternative. It's not much work maintaining it since it is only a very lightweight `lock_api` wrapper and it's always good to have alternative implementations of such fundamental functionality.

**Comment by zesterer** [comment]
@phil-opp Absolutely! I use `spinning_top` in several of my own projects so I'm happy to see it sticking around. Friendly competition is always welcome!
